#pragma once 

#define MOLECULAEXR_TAG_ID_HYDROGEN_MIN 20
#define MOLECULAEXR_TAG_ID_HYDROGEN_MAX 29

#define MOLECULAEXR_TAG_ID_OXYGEN_MIN 30
#define MOLECULAEXR_TAG_ID_OXYGEN_MAX 39

#define MOLECULAEXR_TAG_ID_HYDROGEN_0 20
#define MOLECULAEXR_TAG_ID_HYDROGEN_1 21
#define MOLECULAEXR_TAG_ID_OXYGEN_0   30
#define MOLECULAEXR_EXTERNALY_ID 9999

#define MAX_TAGS_APRILTAG_36H11 587
#define TAG_SIZE_METERS 0.02f
#define TAG_DEBUG_CUBE 10
#define TAG_DEBUG_SPHERE 11

#define MIN_HYDROGEN_OXYGEN_DIST_TO_H2O TAG_SIZE_METERS * 2.3f
#define MIN_HYDROGEN_OXYGEN_DIST_TO_H2O_PLUS_DELTA (MIN_HYDROGEN_OXYGEN_DIST_TO_H2O + TAG_SIZE_METERS * 0.5f)

#define NUM_TOTAL_CHEMICAL_BONDS 512

#define h0_h1_o0_to_h20_index 10

#define MAX_LOST_TIME_TOLERATION 0.3f

#define HYDROGEN_SPHERE_COLOR {0.9f, 0.85f, 0.85f, 1.0f}
#define OXYGEN_SPHERE_COLOR {0.78f, 0.78f, 0.2f, 1.0f}

#define H2O_MOLECULE_COLOR {0.28f, 0.28f, 0.92f, 1.0f}
